### ISSUE TITLE
AWSUpload class expects a `replace` param to be passed

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/pictor#27]
## Describe the bug
The `run` method of the AWSUpload routine expect a `replace` parameter to be passed. There is currently no way for that argument to be passed to that class, nor a way for a user to input that.

## Expected behavior
Clarify the purpose of this parameter. If it's necessary, figure out how that parameter can get passed and persisted in the database. If it's not, then get rid of it.

**Comment by p-galligan** [comment]
Argh, I forgot to deal with that. The purpose of the replace parameter for AWS upload is to replace files in the AWS bucket if the flag is set. If it's not, the upload will throw a FileExists error if it finds an existing matching file.

It might be safe to just remove it, since items should only need to go through the pipeline once, correct?

If we anticipate the need to re-upload for whatever reason we'll have to figure it out.

**Comment by helrond** [comment]
I would have thought the opposite - that we'd want to replace by default. I think this is a question for @bonniegee - how likely are we to accidentally run the same thing through the pipeline twice, and would there be any problems resulting from that? I suppose what we experienced recently with multiple DAO's attached to an archival object is one potential problem, but those should be taken care of via a cleanup process.

**Comment by bonniegee** [comment]
I would also opt for replacing by default. I think that either we'll be re-running stuff through on purpose, in which case we'll want to replace what's up there, or if it's an accident, I agree that the worst-case is not that bad.

I think what we experienced with the DAOs recently is an argument in favor of replacing--we would have ended up with a partial digital object either way.
