### ISSUE TITLE
Compare diff between manifests created in old pipeline and with this microservice

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/pictor#50]
## Is your feature request related to a problem? Please describe.
We should do a very fine-grained comparison of the manifests created by the IIIF pipeline, and those created by pictor.

## Describe the solution you'd like
Run a couple of examples that are already on DIMES through this application, and compare the manifests to what is currently in Cantaloupe.

I tried to find some small-ish examples:
- [An example with photographs](https://dimes.rockarch.org/objects/kpHUChYHXsfoZJdomvyajf/view)
- [An example with documents](https://dimes.rockarch.org/objects/cXgm6WHEz5J5PpdvLnJR9E/view)

## Additional context
Related to #32

**Comment by p-galligan** [comment]
@bonniegee I've added the two below diff files from the old vs new manifests. I generated the new ones using Pictor's development branch.

You'll notice that it incorporates the id url changes, as well as the changes to the Canvas labels (Page numbers). We're getting the page number from the filename instead of incrementing up. This does cause the "first" page of the photographs to be labeled "Page 2", and the first of Mussolini City to be "Page 169". I don't see any other major changes here.

Another set of eyes/sanity check would be appreciated though.

[cXgm6WHEz5J5PpdvLnJR9E_diff.txt](https://github.com/RockefellerArchiveCenter/pictor/files/7157257/cXgm6WHEz5J5PpdvLnJR9E_diff.txt)
[kpHUChYHXsfoZJdomvyajf_diff.txt](https://github.com/RockefellerArchiveCenter/pictor/files/7157258/kpHUChYHXsfoZJdomvyajf_diff.txt)

**Comment by helrond** [comment]
Cool, so one thing which wasn't part of the original issue but I'm now seeing - the annotation IDs. These are currently:
```
https://iiif.rockarch.org/manifests/annotation/kpHUChYHXsfoZJdomvyajf_007.json
```
But I think they should be aligned with the structure we're using for the canvas ids, so:
```
https://iiif.rockarch.org/manifests/kpHUChYHXsfoZJdomvyajf/canvas/0007/annotation/1
```
The `1` at the end is just an identifier for the annotation.

**Comment by helrond** [comment]
Also, I'm seeing that the page numbers in the first example are padded to 5 places - any concern that 4 is not enough @bonniegee (keeping in mind that we may not always be starting at 0).

**Comment by bonniegee** [comment]
Thank you @p-galligan !

As to page numbers starting at 2: going forward the page numbering due to Page 1 being the chargeout will be dealt with before things are sent to Zorya. We will not be saving chargeouts in perpetuity the same way, and there will be a mass deletion of existing chargeouts.

@helrond I'm seeing the padding as 4 places, not 5 places. I upped to 4 from 3, since it seems within the realm of possibility we would have 1,000+ files.

**Comment by helrond** [comment]
@bonniegee cXgm6WHEz5J5PpdvLnJR9E_00169 is five digits, right?

**Comment by bonniegee** [comment]
@helrond That's not happening in the other manifest (which is what I was looking at). Looking more into this, it's because the filenames for those are like "00759.tif". So 1) more leading zeroes than we're using and 2) the page number is the entirety of the filename. The amount of padding is not consistent if you compare the item ID to the image ID.

I did try to handle more leading zeroes than we wanted [(see the lstrip here)](https://github.com/RockefellerArchiveCenter/pictor/blob/8b07f84df2eef927c463c53392235e6ee7cdb8aa/create_derivatives/helpers.py#L51), so I'm going to further dig into why this isn't consistent.

**Comment by p-galligan** [comment]
Re: the annotation id, do we want to file the canvas methodology and just grab id from the file's page number? Or do we just want to increment up from one?

**Comment by helrond** [comment]
@bonniegee simply put, my question is whether we need to pad page numbers to 5 digits, or whether we're absolutely sure that we'll never have a page number over 9,999 (which seems likely, this manifest did give me pause though). 

@p-galligan I think we want to increment up from one, because it's possible to have multiple annotations on a single canvas.

One general comment - looking at these manifests, I think it makes sense for the canvas IDs to NOT have leading zeroes. That way the relationship between the label and the canvas ID is more obvious. As it is now, you need to know that those page numbers are padded out, which we know now but might not always remember in the future.

**Comment by bonniegee** [comment]
@helrond I can't really think of a scenario where we'd have 10,000+ pages. I don't want to encourage workarounds in the future, but I feel like if we were to ever encounter anything that big, we would want to break it up into chunks smaller than 10,000 pages? 

I'm going to push up a PR that includes the annotation change, as well as the canvas ID change.

**Comment by bonniegee** [comment]
Other than the two things covered in #56, are there any concerns from the diff that need to be dealt with?

**Comment by p-galligan** [comment]
I don't see anything. We've just changed around some ids and actually fixed links to manifests.

The label is helpful metadata, but shouldn't break anything. I believe all of the functional stuff has remained the same.

**Comment by helrond** [comment]
If there is a way to confirm that changing the IDs doesn't break anything that would help me sleep better at night.

**Comment by p-galligan** [comment]
We could throw up a manifest and images for something that isn’t already up?

Then we could use mirador to check? I can’t think of any other way.

**Comment by p-galligan** [comment]
Or we could just throw one of these newly minted manifests up and replace the old one. We know the old ones work with mirador and dimes, so if it breaks, it would be related to the manifest.

**Comment by helrond** [comment]
I like that idea - can you test it out @p-galligan? (obviously let's retain the old one in case things go sideways).
