### ISSUE TITLE
Remove PDF services (or allow them to be turned on or off)

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/pictor#88]
## Is your feature request related to a problem? Please describe.
We will, at least temporarily, not be using the PDF services.

## Describe the solution you'd like
Two possible approaches:
1. Remove PDF services from this app entirely.
2. Add a config option, where the PDF services can be skipped (this would mean modifying what process status Create Manifests is looking for).

@helrond , do you have thoughts on which approach makes more sense?

**Comment by helrond** [comment]
Ideally we'd want to have the application figure this out on its own and have branching logic from there, I think. I'm not exactly sure what that looks like though (something with the Origin key?).

In the short term, we need to make minimal changes so that we can simply disable these services in Zodiac and still have the other services in this app run successfully.
